"""Generate the Postgres baseline schema from the SQLite migrations.

The SQLite migration chain (``nexoclip/db/migrations/*.sql``) is the source
of truth for the schema. Rather than hand-port 46 files to Postgres, we:

  1. apply every migration to a throwaway SQLite database,
  2. read the resulting end-state DDL from ``sqlite_master``,
  3. translate SQLite DDL → Postgres DDL (types + comment stripping),
  4. topologically sort tables by foreign-key dependency (Postgres requires
     a referenced table to already exist at CREATE time; SQLite doesn't),
  5. write ``nexoclip/db/pg_baseline.sql``.

Re-run this whenever the migration chain changes (then review the diff and
bump the baseline version constant in the migration runner).

Usage:  python scripts/gen_pg_baseline.py
"""

from __future__ import annotations

import asyncio
import re
import tempfile
from pathlib import Path

from nexoclip.db import Database, apply_migrations

_OUT = Path(__file__).parent.parent / "nexoclip" / "db" / "pg_baseline.sql"

# Type substitutions (whole-word, case-insensitive). SQLite's loose affinity
# types map to permissive Postgres types so the existing Python value types
# (str/int/float/bytes) bind without asyncpg complaining, and so 0/1 integer
# "booleans" keep working without a bool/int dance.
_TYPE_SUBS = [
    (re.compile(r"\bINTEGER\b", re.IGNORECASE), "bigint"),
    (re.compile(r"\bREAL\b", re.IGNORECASE), "double precision"),
    (re.compile(r"\bBLOB\b", re.IGNORECASE), "bytea"),
]

# `-- ...` line comments → dropped (keeps the baseline terse and avoids any
# chance a comment word collides with a type substitution).
_LINE_COMMENT = re.compile(r"--[^\n]*")

# Pull referenced table names out of inline `REFERENCES <tbl>(...)` clauses.
_REFERENCES = re.compile(r"REFERENCES\s+\"?(\w+)\"?", re.IGNORECASE)
_TABLE_NAME = re.compile(r"CREATE TABLE\s+\"?(\w+)\"?", re.IGNORECASE)


def _translate(ddl: str) -> str:
    ddl = _LINE_COMMENT.sub("", ddl)
    for pat, repl in _TYPE_SUBS:
        ddl = pat.sub(repl, ddl)
    # Collapse the blank lines left by comment stripping.
    lines = [ln.rstrip() for ln in ddl.splitlines()]
    return "\n".join(ln for ln in lines if ln.strip())


def _toposort(tables: dict[str, str]) -> list[str]:
    """Return table names ordered so every FK target precedes its referrer.

    Kahn's algorithm with an alphabetical tie-break for deterministic output.
    Self-references and references to non-baseline tables are ignored.
    """
    deps: dict[str, set[str]] = {}
    for name, ddl in tables.items():
        refs = {r.lower() for r in _REFERENCES.findall(ddl)}
        refs.discard(name.lower())
        deps[name] = {r for r in refs if r in tables}

    ordered: list[str] = []
    remaining = dict(deps)
    while remaining:
        ready = sorted(n for n, d in remaining.items() if d <= set(ordered))
        if not ready:
            raise SystemExit(f"FK cycle among: {sorted(remaining)}")
        for n in ready:
            ordered.append(n)
            del remaining[n]
    return ordered


async def main() -> None:
    tmp = Path(tempfile.gettempdir()) / "pg_baseline_src.db"
    if tmp.exists():
        tmp.unlink()
    db = Database(tmp)
    version = await apply_migrations(db)
    conn = await db.connect()
    cur = await conn.execute(
        "SELECT type, name, sql FROM sqlite_master "
        "WHERE sql IS NOT NULL ORDER BY name"
    )
    rows = await cur.fetchall()
    await db.close()

    tables: dict[str, str] = {}
    indexes: list[str] = []
    for type_, name, sql in rows:
        if name == "schema_version":
            continue  # the migration runner owns this table
        if type_ == "table":
            m = _TABLE_NAME.search(sql)
            tables[m.group(1)] = sql  # type: ignore[union-attr]
        elif type_ == "index":
            indexes.append(sql)

    order = _toposort(tables)

    parts = [
        "-- GENERATED by scripts/gen_pg_baseline.py — do not edit by hand.",
        f"-- Postgres baseline equivalent to SQLite migrations through v{version}.",
        "-- Tables are FK-topologically ordered for Postgres CREATE-time checks.",
        "",
    ]
    for name in order:
        parts.append(_translate(tables[name]) + ";")
        parts.append("")
    for idx in sorted(indexes):
        parts.append(_translate(idx) + ";")
    parts.append("")

    _OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {_OUT} — {len(tables)} tables, {len(indexes)} indexes, v{version}")


if __name__ == "__main__":
    asyncio.run(main())
