"""Forward-only migration runner.

Migrations live in `nexoclip/db/migrations/` as `NNN_<name>.sql`.
Schema version is tracked in the single-row `schema_version` table.
"""

from __future__ import annotations

import re
from pathlib import Path

import aiosqlite

from nexoclip.errors import NexoClipError

from .connection import Database

_MIGRATION_RE = re.compile(r"^(\d{3})_([a-z0-9_]+)\.sql$", re.IGNORECASE)

# The consolidated Postgres schema. SQLite migrations are dialect-specific
# and can't replay on Postgres, so the asyncpg backend applies this single
# baseline instead (generated by scripts/gen_pg_baseline.py). Its header
# records the migration version it was generated at; we assert that matches
# the SQLite chain's head so a forgotten regen fails loudly instead of
# silently drifting the schema.
_PG_BASELINE_PATH = Path(__file__).parent / "pg_baseline.sql"
_PG_BASELINE_VERSION_RE = re.compile(r"through v(\d+)", re.IGNORECASE)


class MigrationError(NexoClipError):
    """Migration runner failure."""


async def _ensure_schema_version_table(conn: aiosqlite.Connection) -> int:
    """Return the current schema version, creating the table on first run."""
    await conn.execute(
        """
        CREATE TABLE IF NOT EXISTS schema_version (
            rowid   INTEGER PRIMARY KEY CHECK (rowid = 1),
            version INTEGER NOT NULL
        )
        """
    )
    await conn.commit()
    cur = await conn.execute("SELECT version FROM schema_version WHERE rowid = 1")
    row = await cur.fetchone()
    return int(row[0]) if row else 0


def _discover_migrations(directory: Path) -> list[tuple[int, str, Path]]:
    """Sorted (version, name, path) for every well-named .sql in `directory`."""
    out: list[tuple[int, str, Path]] = []
    for candidate in sorted(directory.glob("*.sql")):
        m = _MIGRATION_RE.match(candidate.name)
        if not m:
            raise MigrationError(
                f"migration filename does not match NNN_<name>.sql: {candidate.name}"
            )
        out.append((int(m.group(1)), m.group(2), candidate))
    out.sort()
    return out


def _pg_baseline_version() -> int:
    """The migration version the Postgres baseline was generated at."""
    head = _PG_BASELINE_PATH.read_text(encoding="utf-8")[:512]
    m = _PG_BASELINE_VERSION_RE.search(head)
    if not m:
        raise MigrationError(
            f"{_PG_BASELINE_PATH.name} is missing its 'through vN' version header; "
            "regenerate it with scripts/gen_pg_baseline.py"
        )
    return int(m.group(1))


async def _apply_pg_baseline(db: Database, target: int) -> int:
    """Apply the consolidated Postgres baseline to a fresh database.

    The asyncpg backend can't replay the SQLite migration files, so a fresh
    Postgres database gets the single baseline schema instead, then its
    version is stamped to the head of the SQLite chain. Idempotent: a
    database already at/above the baseline is a no-op.
    """
    if not _PG_BASELINE_PATH.exists():
        raise MigrationError(f"Postgres baseline not found: {_PG_BASELINE_PATH}")
    baseline_version = _pg_baseline_version()
    if baseline_version != target:
        raise MigrationError(
            f"pg_baseline.sql is at v{baseline_version} but the SQLite migration "
            f"chain head is v{target}; regenerate with scripts/gen_pg_baseline.py"
        )

    conn = await db.connect()
    current = await _ensure_schema_version_table(conn)
    if current >= target:
        return current
    if current != 0:
        # A partially-migrated SQLite database can't be upgraded by the
        # baseline (it only knows the end state). Fresh Postgres only.
        raise MigrationError(
            f"Postgres backend expects a fresh database, but schema_version={current}. "
            "Use the data-migration tooling to move an existing SQLite database."
        )
    await conn.executescript(_PG_BASELINE_PATH.read_text(encoding="utf-8"))
    await conn.execute(
        "INSERT INTO schema_version (rowid, version) VALUES (1, ?) "
        "ON CONFLICT (rowid) DO UPDATE SET version = excluded.version",
        (target,),
    )
    await conn.commit()
    return target


async def apply_migrations(db: Database, *, migrations_dir: Path | None = None) -> int:
    """Apply any pending migrations. Returns the resulting schema version."""
    if migrations_dir is None:
        migrations_dir = Path(__file__).parent / "migrations"
    if not migrations_dir.exists():
        raise MigrationError(f"migrations dir not found: {migrations_dir}")

    available = _discover_migrations(migrations_dir)
    if not available:
        raise MigrationError(f"no migrations found in {migrations_dir}")

    versions = [v for v, _, _ in available]
    if versions != list(range(1, len(versions) + 1)):
        raise MigrationError(
            f"migration versions must be a contiguous 1..N sequence; got {versions}"
        )

    # Postgres: one consolidated baseline instead of replaying SQLite files.
    if getattr(db, "is_postgres", False):
        return await _apply_pg_baseline(db, available[-1][0])

    conn = await db.connect()
    current = await _ensure_schema_version_table(conn)
    target = available[-1][0]

    if current > target:
        raise MigrationError(
            f"schema_version={current} is newer than highest available migration={target}; "
            "downgrades are not supported"
        )

    for version, _name, path in available:
        if version <= current:
            continue
        sql = path.read_text(encoding="utf-8")
        try:
            # executescript implicitly commits any pending tx, then runs the
            # script as a single statement batch. We follow it with the
            # version bump so a partial failure leaves schema_version stale
            # (re-runnable migration files should be safe to retry).
            await conn.executescript(sql)
            await conn.execute(
                "INSERT OR REPLACE INTO schema_version (rowid, version) VALUES (1, ?)",
                (version,),
            )
            await conn.commit()
        except Exception as e:
            await conn.rollback()
            raise MigrationError(f"migration {path.name} failed: {e}") from e
        current = version

    return current


async def schema_version(db: Database) -> int:
    """Read the current schema version (0 if uninitialized)."""
    conn = await db.connect()
    return await _ensure_schema_version_table(conn)
