-- GENERATED by scripts/gen_pg_baseline.py — do not edit by hand.
-- Postgres baseline equivalent to SQLite migrations through v47.
-- Tables are FK-topologically ordered for Postgres CREATE-time checks.

CREATE TABLE platform_settings (
    key        TEXT PRIMARY KEY,
    value      TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE tenants (
    id         TEXT PRIMARY KEY,
    name       TEXT NOT NULL,
    created_at TEXT NOT NULL
, daily_llm_budget_usd_micros bigint, daily_publish_limit         bigint, rescore_concurrency_cap     bigint NOT NULL DEFAULT 4, retention_vod_days bigint, retention_clip_days bigint, retention_transcript_days bigint, tier TEXT NOT NULL DEFAULT 'free', external_user_id TEXT, status TEXT NOT NULL DEFAULT 'active'
  CHECK (status IN ('active', 'paused', 'cancelled')), cached_balance_remaining bigint, cached_balance_unlimited bigint NOT NULL DEFAULT 0, cached_balance_monthly_used bigint, cached_balance_at TEXT, upload_post_profile_username TEXT, last_usage_report_at    TEXT, last_usage_report_ok    bigint, last_usage_report_error TEXT, zernio_profile_id TEXT, zernio_profile_name TEXT);

CREATE TABLE zernio_auto_retries (
    post_id      TEXT PRIMARY KEY,
    tenant_id    TEXT,
    attempted_at TEXT NOT NULL,
    outcome      TEXT
);

CREATE TABLE zernio_calendar (
    account_id    TEXT NOT NULL,
    post_id       TEXT NOT NULL,
    platform      TEXT,
    content       TEXT,
    url           TEXT,
    thumbnail_url TEXT,
    media_type    TEXT,
    published_at  TEXT,
    status        TEXT NOT NULL DEFAULT 'active',
    deleted_at    TEXT,
    updated_at    TEXT NOT NULL,
    PRIMARY KEY (account_id, post_id)
);

CREATE TABLE zernio_comments (
    account_id       TEXT NOT NULL,
    comment_id       TEXT NOT NULL,
    post_id          TEXT,
    platform_post_id TEXT,
    platform         TEXT,
    text             TEXT,
    author_id        TEXT,
    author_name      TEXT,
    author_username  TEXT,
    is_reply         bigint NOT NULL DEFAULT 0,
    parent_id        TEXT,
    status           TEXT NOT NULL DEFAULT 'active',
    created_at       TEXT,
    received_at      TEXT NOT NULL,
    PRIMARY KEY (account_id, comment_id)
);

CREATE TABLE zernio_community_notifications (
    source_post_id       TEXT PRIMARY KEY,
    tenant_id            TEXT NOT NULL,
    notification_post_id TEXT,
    sent_at              TEXT NOT NULL
);

CREATE TABLE zernio_contacts (
    account_id    TEXT NOT NULL,
    contact_key   TEXT NOT NULL,
    platform      TEXT,
    name          TEXT,
    username      TEXT,
    tags          TEXT,
    zernio_contact_id TEXT,
    first_seen    TEXT NOT NULL,
    last_seen     TEXT NOT NULL,
    PRIMARY KEY (account_id, contact_key)
);

CREATE TABLE zernio_conversations (
    account_id            TEXT NOT NULL,
    conversation_id       TEXT NOT NULL,
    platform              TEXT,
    participant_id        TEXT,
    participant_name      TEXT,
    participant_username  TEXT,
    status                TEXT NOT NULL DEFAULT 'active',
    last_message_at       TEXT,
    updated_at            TEXT NOT NULL,
    PRIMARY KEY (account_id, conversation_id)
);

CREATE TABLE zernio_events (
    event_id     TEXT PRIMARY KEY,
    type         TEXT NOT NULL,
    payload      TEXT NOT NULL,
    profile_id   TEXT,
    tenant_id    TEXT,
    received_at  TEXT NOT NULL,
    processed    bigint NOT NULL DEFAULT 0,
    processed_at TEXT
);

CREATE TABLE zernio_messages (
    account_id       TEXT NOT NULL,
    message_id       TEXT NOT NULL,
    conversation_id  TEXT,
    platform         TEXT,
    direction        TEXT,
    text             TEXT,
    sent_at          TEXT,
    is_read          bigint NOT NULL DEFAULT 0,
    received_at      TEXT NOT NULL,
    PRIMARY KEY (account_id, message_id)
);

CREATE TABLE zernio_whatsapp_numbers (
    account_id  TEXT PRIMARY KEY,
    status      TEXT NOT NULL,
    detail      TEXT,
    updated_at  TEXT NOT NULL
);

CREATE TABLE api_tokens (
    id           TEXT PRIMARY KEY,
    tenant_id    TEXT NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    hash         TEXT NOT NULL UNIQUE,
    scope        TEXT NOT NULL DEFAULT 'full',
    created_at   TEXT NOT NULL,
    last_used_at TEXT
);

CREATE TABLE autopublish_settings (
    tenant_id   TEXT PRIMARY KEY,
    enabled     bigint NOT NULL DEFAULT 0,
    mode        TEXT NOT NULL DEFAULT 'on_approve',
    targets     TEXT,
    post_mode   TEXT NOT NULL DEFAULT 'queue',
    daily_cap   bigint NOT NULL DEFAULT 10,
    updated_at  TEXT NOT NULL, score_threshold double precision NOT NULL DEFAULT 0.6, tag_suffix TEXT NOT NULL DEFAULT '',
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE brand_kits (
    id                        TEXT PRIMARY KEY,
    tenant_id                 TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name                      TEXT NOT NULL,
    is_default                bigint NOT NULL DEFAULT 0,
    primary_color             TEXT NOT NULL,
    accent_color              TEXT NOT NULL,
    text_color                TEXT NOT NULL DEFAULT '#FFFFFF',
    font_family               TEXT NOT NULL DEFAULT 'Inter',
    font_weight               bigint NOT NULL DEFAULT 800,
    logo_url                  TEXT,
    logo_dark_url             TEXT,
    watermark_url             TEXT,
    intro_sting_url           TEXT,
    outro_sting_url           TEXT,
    caption_style_json        TEXT,
    default_layout            TEXT NOT NULL DEFAULT 'pip',
    handle_tiktok             TEXT,
    handle_youtube            TEXT,
    handle_instagram          TEXT,
    handle_kick               TEXT,
    ai_generated              bigint NOT NULL DEFAULT 0,
    ai_prompt                 TEXT,
    ai_provider               TEXT,
    auto_publish_enabled      bigint NOT NULL DEFAULT 0,
    auto_publish_platforms_json TEXT,
    auto_publish_delay_min    bigint NOT NULL DEFAULT 60,
    custom_trigger_phrases_json TEXT,
    created_at                TEXT NOT NULL,
    updated_at                TEXT NOT NULL
, default_platform           TEXT, banner_enabled_default     bigint NOT NULL DEFAULT 0, banner_show_context_default  bigint NOT NULL DEFAULT 0, banner_show_safezones_default bigint NOT NULL DEFAULT 0, clip_style                   TEXT, bottom_banner_style          TEXT, banner_live_badge_default    bigint NOT NULL DEFAULT 0, top_hook_enabled_default     bigint NOT NULL DEFAULT 0, top_hook_style_default       TEXT, target_platform TEXT, show_nexoclip_credit bigint NOT NULL DEFAULT 1, safe_schedule_enabled bigint NOT NULL DEFAULT 0, safety_policy_json TEXT, content_timezone TEXT NOT NULL DEFAULT 'UTC');

CREATE TABLE channel_watches (
    id                  TEXT PRIMARY KEY,
    tenant_id           TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    platform            TEXT NOT NULL,
    channel_url         TEXT NOT NULL,
    channel_label       TEXT,
    persona_id          TEXT NOT NULL,
    language            TEXT,
    last_polled_at      TEXT,
    seen_video_ids_json TEXT NOT NULL DEFAULT '[]',
    max_per_poll        bigint NOT NULL DEFAULT 3,
    enabled             bigint NOT NULL DEFAULT 1,
    created_at          TEXT NOT NULL,
    updated_at          TEXT NOT NULL, polls_per_day bigint NOT NULL DEFAULT 1,
    UNIQUE (tenant_id, channel_url)
);

CREATE TABLE connected_accounts (
    id              TEXT PRIMARY KEY,
    tenant_id       TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    platform        TEXT NOT NULL,
    external_id     TEXT NOT NULL,
    display_name    TEXT,
    oauth_blob_json TEXT,
    created_at      TEXT NOT NULL
, refresh_token TEXT, expires_at    TEXT, scopes_json   TEXT, status        TEXT NOT NULL DEFAULT 'active', access_token_encrypted   bytea, refresh_token_encrypted  bytea, token_type               TEXT, platform_user_id         TEXT, platform_username        TEXT, platform_avatar_url      TEXT, daily_publish_count      bigint NOT NULL DEFAULT 0, daily_publish_window_start TEXT);

CREATE TABLE drive_export_settings (
    tenant_id                TEXT PRIMARY KEY REFERENCES tenants(id) ON DELETE CASCADE,
    enabled                  bigint NOT NULL DEFAULT 0,
    folder_id                TEXT,
    folder_name              TEXT,
    refresh_token            TEXT,
    access_token             TEXT,
    access_token_expires_at  TEXT,
    created_at               TEXT NOT NULL,
    updated_at               TEXT NOT NULL
);

CREATE TABLE drive_watches (
    id                       TEXT PRIMARY KEY,
    tenant_id                TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    folder_id                TEXT NOT NULL,
    folder_name              TEXT,
    refresh_token            TEXT NOT NULL,
    access_token             TEXT,
    access_token_expires_at  TEXT,
    last_polled_at           TEXT,
    seen_file_ids_json       TEXT NOT NULL DEFAULT '[]',
    enabled                  bigint NOT NULL DEFAULT 1,
    created_at               TEXT NOT NULL,
    updated_at               TEXT NOT NULL,
    UNIQUE (tenant_id, folder_id)
);

CREATE TABLE events (
    id           TEXT PRIMARY KEY,
    tenant_id    TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    type         TEXT NOT NULL,
    payload_json TEXT NOT NULL DEFAULT '{}',
    ts           TEXT NOT NULL
);

CREATE TABLE hub_publish_jobs (
    job_id          TEXT PRIMARY KEY,
    tenant_id       TEXT NOT NULL,
    idempotency_key TEXT,
    source          TEXT NOT NULL,
    mode            TEXT NOT NULL,
    targets         TEXT NOT NULL,
    video_url       TEXT NOT NULL,
    title           TEXT,
    caption         TEXT,
    scheduled_for   TEXT,
    zernio_post_id  TEXT,
    status          TEXT NOT NULL DEFAULT 'pending',
    platforms_json  TEXT,
    error           TEXT,
    created_at      TEXT NOT NULL,
    updated_at      TEXT,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE live_stream_keys (
    id            TEXT PRIMARY KEY,
    tenant_id     TEXT NOT NULL,
    key_value     TEXT NOT NULL UNIQUE,
    created_at    TEXT NOT NULL,
    revoked_at    TEXT,
    last_used_at  TEXT,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE llm_calls (
    id               TEXT PRIMARY KEY,
    tenant_id        TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    purpose          TEXT NOT NULL,
    provider         TEXT NOT NULL,
    model            TEXT NOT NULL,
    quality          TEXT NOT NULL,
    input_tokens     bigint NOT NULL DEFAULT 0,
    output_tokens    bigint NOT NULL DEFAULT 0,
    cost_usd_micros  bigint NOT NULL DEFAULT 0,
    status           TEXT NOT NULL DEFAULT 'ok',
    error            TEXT,
    attempts         bigint NOT NULL DEFAULT 1,
    ts               TEXT NOT NULL
, stream_id TEXT);

CREATE TABLE personas (
    id                    TEXT PRIMARY KEY,
    tenant_id             TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name                  TEXT NOT NULL,
    primary_language      TEXT NOT NULL,
    target_languages_json TEXT NOT NULL DEFAULT '[]',
    voice_prompt          TEXT NOT NULL,
    routing_tags_json     TEXT NOT NULL DEFAULT '[]',
    created_at            TEXT NOT NULL
);

CREATE TABLE stream_destinations (
    id              TEXT PRIMARY KEY,
    tenant_id       TEXT NOT NULL,
    platform        TEXT NOT NULL,
    label           TEXT,
    ingest_url      TEXT NOT NULL,
    stream_key_enc  TEXT NOT NULL,
    enabled         bigint NOT NULL DEFAULT 1,
    last_status     TEXT,
    last_status_at  TEXT,
    created_at      TEXT NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE streams (
    id                 TEXT PRIMARY KEY,
    tenant_id          TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    vod_url            TEXT NOT NULL,
    platform           TEXT NOT NULL,
    title              TEXT,
    channel            TEXT,
    duration_s         double precision NOT NULL,
    source_video_path  TEXT NOT NULL,
    source_audio_path  TEXT NOT NULL,
    status             TEXT NOT NULL DEFAULT 'ingested',
    created_at         TEXT NOT NULL
, is_live bigint NOT NULL DEFAULT 0, live_started_at TEXT, live_ended_at TEXT);

CREATE TABLE users (
    id         TEXT PRIMARY KEY,
    tenant_id  TEXT NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    email      TEXT NOT NULL,
    role       TEXT NOT NULL DEFAULT 'owner',
    created_at TEXT NOT NULL,
    UNIQUE (tenant_id, email)
);

CREATE TABLE webhook_subscriptions (
    id                TEXT PRIMARY KEY,
    tenant_id         TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    url               TEXT NOT NULL,
    types_json        TEXT NOT NULL DEFAULT '[]',
    secret            TEXT NOT NULL,
    status            TEXT NOT NULL DEFAULT 'active',
    created_at        TEXT NOT NULL,
    last_dispatch_ts  TEXT,
    failure_count     bigint NOT NULL DEFAULT 0
);

CREATE TABLE zernio_broadcast_log (
    id           TEXT PRIMARY KEY,
    tenant_id    TEXT NOT NULL,
    broadcast_id TEXT NOT NULL,
    day          TEXT NOT NULL,
    sent_at      TEXT NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE zernio_community_settings (
    tenant_id           TEXT PRIMARY KEY,
    enabled             bigint NOT NULL DEFAULT 0,
    discord_account_id  TEXT,
    telegram_account_id TEXT,
    brand_name          TEXT,
    brand_avatar_url    TEXT,
    weekly_digest       bigint NOT NULL DEFAULT 0,
    updated_at          TEXT NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE zernio_publish_snapshots (
    id            TEXT PRIMARY KEY,
    tenant_id     TEXT NOT NULL,
    post_id       TEXT NOT NULL,
    day           TEXT NOT NULL,
    metrics_json  TEXT NOT NULL,
    platforms_json TEXT,
    captured_at   TEXT NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE zernio_publishes (
    post_id     TEXT PRIMARY KEY,
    tenant_id   TEXT NOT NULL,
    clip_id     TEXT NOT NULL,
    platforms   TEXT NOT NULL,
    content     TEXT,
    created_at  TEXT NOT NULL, status TEXT, platforms_json TEXT, updated_at TEXT, options_json TEXT,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE candidates (
    id            TEXT PRIMARY KEY,
    stream_id     TEXT NOT NULL REFERENCES streams(id) ON DELETE CASCADE,
    tenant_id     TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    ts            double precision NOT NULL,
    score         double precision NOT NULL,
    reason        TEXT NOT NULL,
    evidence_json TEXT NOT NULL DEFAULT '{}',
    created_at    TEXT NOT NULL
, rescore_score  double precision, rescore_reason TEXT, rescore_model  TEXT);

CREATE TABLE "speakers" (
    id                        TEXT PRIMARY KEY,
    tenant_id                 TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    display_name              TEXT NOT NULL,
    is_self                   bigint NOT NULL DEFAULT 0,
    preferred_brand_kit_id    TEXT REFERENCES brand_kits(id) ON DELETE SET NULL,
    embedding_json            TEXT,
    embedding_dim             bigint,
    total_speech_s            double precision NOT NULL DEFAULT 0.0,
    sample_audio_path         TEXT,
    created_at                TEXT NOT NULL,
    updated_at                TEXT NOT NULL
);

CREATE TABLE transcripts (
    stream_id     TEXT PRIMARY KEY REFERENCES streams(id) ON DELETE CASCADE,
    tenant_id     TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    language      TEXT NOT NULL,
    duration_s    double precision NOT NULL,
    model         TEXT NOT NULL,
    segments_json TEXT NOT NULL,
    created_at    TEXT NOT NULL
);

CREATE TABLE visual_signals (
    stream_id     TEXT NOT NULL REFERENCES streams(id) ON DELETE CASCADE,
    tenant_id     TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    ts_offset_s   double precision NOT NULL,
    scene_cut     bigint NOT NULL DEFAULT 0,
    face_emotion  TEXT,
    motion_energy double precision,
    text_changed  bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (stream_id, ts_offset_s)
);

CREATE TABLE webhook_secret_versions (
    id              TEXT PRIMARY KEY,
    subscription_id TEXT NOT NULL REFERENCES webhook_subscriptions(id) ON DELETE CASCADE,
    tenant_id       TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    secret          TEXT NOT NULL,
    expires_at      TEXT NOT NULL,
    created_at      TEXT NOT NULL
);

CREATE TABLE clips (
    id                   TEXT PRIMARY KEY,
    stream_id            TEXT NOT NULL REFERENCES streams(id) ON DELETE CASCADE,
    tenant_id            TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    candidate_id         TEXT REFERENCES candidates(id) ON DELETE SET NULL,
    start_s              double precision NOT NULL,
    end_s                double precision NOT NULL,
    duration_s           double precision NOT NULL,
    width                bigint NOT NULL,
    height               bigint NOT NULL,
    path                 TEXT NOT NULL,
    smart_crop_box_json  TEXT,
    thumbnail_frame_path TEXT,
    status               TEXT NOT NULL DEFAULT 'cut',
    created_at           TEXT NOT NULL
, overlay_config_json TEXT, publishability_score bigint, publishability_status TEXT, original_start_s double precision, original_end_s double precision, render_state TEXT NOT NULL DEFAULT 'idle', render_progress_pct bigint NOT NULL DEFAULT 0, render_error TEXT, render_started_at TEXT);

CREATE TABLE vod_speakers (
    id                    TEXT PRIMARY KEY,
    stream_id             TEXT NOT NULL REFERENCES streams(id) ON DELETE CASCADE,
    tenant_id             TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    speaker_label         TEXT NOT NULL,
    resolved_speaker_id   TEXT REFERENCES speakers(id) ON DELETE SET NULL,
    confidence            double precision,
    total_speech_s        double precision NOT NULL DEFAULT 0.0,
    embedding_json        TEXT,
    created_at            TEXT NOT NULL,
    UNIQUE (stream_id, speaker_label)
);

CREATE TABLE variants (
    id               TEXT PRIMARY KEY,
    clip_id          TEXT NOT NULL REFERENCES clips(id) ON DELETE CASCADE,
    tenant_id        TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    persona_id       TEXT NOT NULL REFERENCES personas(id) ON DELETE CASCADE,
    language         TEXT NOT NULL,
    caption          TEXT NOT NULL,
    title_card_text  TEXT NOT NULL DEFAULT '',
    hashtags_json    TEXT NOT NULL DEFAULT '[]',
    model            TEXT,
    created_at       TEXT NOT NULL
);

CREATE TABLE publish_jobs (
    id             TEXT PRIMARY KEY,
    tenant_id      TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    clip_id        TEXT NOT NULL REFERENCES clips(id) ON DELETE CASCADE,
    variant_id     TEXT NOT NULL REFERENCES variants(id) ON DELETE CASCADE,
    account_id     TEXT NOT NULL REFERENCES connected_accounts(id) ON DELETE RESTRICT,
    platform       TEXT NOT NULL,
    status         TEXT NOT NULL DEFAULT 'pending',
    attempts       bigint NOT NULL DEFAULT 0,
    last_error     TEXT,
    scheduled_for  TEXT,
    external_id    TEXT,
    created_at     TEXT NOT NULL
, external_url           TEXT, platform_metadata_json TEXT);

CREATE TABLE publish_metrics (
    id                  TEXT PRIMARY KEY,
    tenant_id           TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    publish_job_id      TEXT NOT NULL REFERENCES publish_jobs(id) ON DELETE CASCADE,
    platform            TEXT NOT NULL,
    fetched_at          TEXT NOT NULL,
    views               bigint,
    likes               bigint,
    comments            bigint,
    shares              bigint,
    retention_pct       double precision,
    ctr                 double precision,
    raw_metadata_json   TEXT,
    created_at          TEXT NOT NULL
);

CREATE INDEX idx_api_tokens_tenant ON api_tokens (tenant_id);
CREATE INDEX idx_brand_kits_tenant ON brand_kits (tenant_id);
CREATE INDEX idx_broadcast_log_tenant_day
    ON zernio_broadcast_log (tenant_id, day);
CREATE INDEX idx_calendar_account_date
    ON zernio_calendar (account_id, published_at DESC);
CREATE INDEX idx_candidates_tenant_stream ON candidates (tenant_id, stream_id, ts);
CREATE INDEX idx_channel_watches_tenant_enabled
    ON channel_watches (tenant_id, enabled);
CREATE INDEX idx_clips_publishability_status
  ON clips (tenant_id, publishability_status);
CREATE INDEX idx_clips_render_state
    ON clips (tenant_id, render_state)
    WHERE render_state IN ('rendering', 'failed');
CREATE INDEX idx_clips_stream ON clips (stream_id);
CREATE INDEX idx_clips_tenant_created ON clips (tenant_id, created_at);
CREATE INDEX idx_comments_account
    ON zernio_comments (account_id, created_at DESC);
CREATE INDEX idx_comments_post
    ON zernio_comments (platform_post_id);
CREATE INDEX idx_community_notif_post
    ON zernio_community_notifications (notification_post_id);
CREATE INDEX idx_connected_accounts_platform_user
    ON connected_accounts (tenant_id, platform, platform_user_id);
CREATE INDEX idx_connected_accounts_tenant ON connected_accounts (tenant_id);
CREATE INDEX idx_connected_accounts_tenant_status ON connected_accounts (tenant_id, status);
CREATE INDEX idx_contacts_account
    ON zernio_contacts (account_id, last_seen DESC);
CREATE INDEX idx_conversations_account
    ON zernio_conversations (account_id, last_message_at DESC);
CREATE INDEX idx_drive_watches_tenant_enabled
    ON drive_watches (tenant_id, enabled);
CREATE INDEX idx_events_tenant_ts ON events (tenant_id, ts);
CREATE INDEX idx_events_tenant_type ON events (tenant_id, type, ts);
CREATE INDEX idx_hub_jobs_post
    ON hub_publish_jobs (zernio_post_id);
CREATE INDEX idx_hub_jobs_tenant
    ON hub_publish_jobs (tenant_id, created_at DESC);
CREATE INDEX idx_live_stream_keys_active
    ON live_stream_keys(tenant_id)
    WHERE revoked_at IS NULL;
CREATE INDEX idx_llm_calls_stream ON llm_calls (stream_id);
CREATE INDEX idx_llm_calls_tenant_ts ON llm_calls (tenant_id, ts);
CREATE INDEX idx_messages_conversation
    ON zernio_messages (account_id, conversation_id, sent_at);
CREATE INDEX idx_personas_tenant ON personas (tenant_id);
CREATE INDEX idx_publish_jobs_tenant_status ON publish_jobs (tenant_id, status, scheduled_for);
CREATE INDEX idx_publish_metrics_tenant_job_fetched
    ON publish_metrics (tenant_id, publish_job_id, fetched_at);
CREATE INDEX idx_publish_metrics_tenant_platform_fetched
    ON publish_metrics (tenant_id, platform, fetched_at);
CREATE INDEX idx_snapshots_tenant
    ON zernio_publish_snapshots (tenant_id, day DESC);
CREATE INDEX idx_speakers_tenant ON speakers (tenant_id);
CREATE INDEX idx_stream_destinations_tenant
    ON stream_destinations (tenant_id);
CREATE INDEX idx_streams_tenant_created ON streams (tenant_id, created_at);
CREATE INDEX idx_streams_tenant_vod
    ON streams (tenant_id, vod_url);
CREATE INDEX idx_tenants_status ON tenants(status);
CREATE INDEX idx_transcripts_tenant ON transcripts (tenant_id);
CREATE INDEX idx_users_tenant ON users (tenant_id);
CREATE INDEX idx_variants_clip ON variants (clip_id);
CREATE INDEX idx_variants_tenant_created ON variants (tenant_id, created_at);
CREATE INDEX idx_visual_signals_tenant ON visual_signals (tenant_id, stream_id, ts_offset_s);
CREATE INDEX idx_vod_speakers_speaker ON vod_speakers (tenant_id, resolved_speaker_id);
CREATE INDEX idx_vod_speakers_stream ON vod_speakers (stream_id);
CREATE INDEX idx_vod_speakers_tenant ON vod_speakers (tenant_id);
CREATE INDEX idx_webhook_secret_versions_sub
    ON webhook_secret_versions (tenant_id, subscription_id, expires_at);
CREATE INDEX idx_webhook_subscriptions_tenant ON webhook_subscriptions (tenant_id, status);
CREATE INDEX idx_zernio_events_tenant
    ON zernio_events (tenant_id, received_at DESC);
CREATE INDEX idx_zernio_events_unprocessed
    ON zernio_events (processed, received_at);
CREATE INDEX idx_zernio_publishes_tenant
    ON zernio_publishes (tenant_id, created_at DESC);
CREATE UNIQUE INDEX idx_brand_kits_one_default_per_tenant
    ON brand_kits (tenant_id)
    WHERE is_default = 1;
CREATE UNIQUE INDEX idx_hub_jobs_idem
    ON hub_publish_jobs (tenant_id, idempotency_key)
    WHERE idempotency_key IS NOT NULL;
CREATE UNIQUE INDEX idx_snapshots_post_day
    ON zernio_publish_snapshots (post_id, day);
CREATE UNIQUE INDEX idx_tenants_external_user_id
  ON tenants(external_user_id)
  WHERE external_user_id IS NOT NULL;
